### ISSUE TITLE
漫画柜parser的一点疑问

### ISSUE THREAD

**Issue by Lcatss** [axlecho/manhuaapi#1]
我最近在写一个漫画柜的爬虫，
我看到代码里获取图片的参数是这样拼接的，val token = "?cid=${info.cid}&md5=${info.sl.md5}"，
但是我用chrome抓包得到的url是这样的，https://i.hamreus.com/ps3/y/yiquanchaoren/%E7%AC%AC174%E8%AF%9D/1587618684XcjItI6TefLHDlBU.jpg.webp?e=1594338930&m=Ok45cQ_QoelacxafjcPZCg
是一个叫e和一个叫m的参数。
不过MHViewer访问漫画柜时，解析并没有问题，所以我有点困惑，是parser部分的代码更新了没有上传吗？还是说我访问的方式有问题呢

**Comment by axlecho** [comment]
代码都已开源
e与m看样子是登录会话相关的，去掉也没关系
你可以看下API里漫画柜的单元测试
